#!/bin/bash

#
# Reset the time on your Boot2Docker VM, which can fall out of
# sync when your Mac goes into standby mode. Basically a wrapper for
# [cpuguy83](https://github.com/cpuguy83)'s NTP update container.
#
# by Matt Cloyd aka [beechnut](https://github.com/beechnut)
# Based on [boot2docker-fwd](https://gist.github.com/deinspanjer/9215467)
#       by [deinspanjer](https://github.com/deinspanjer)
#

usage ()
{
  cat <<UsageHERE
boot2docker-ntp -- Helper function to reset the time on the boot2docker-vm.
Usage: boot2docker-ntp [ -s NTP_SERVER ] [ -h ]
Options:
 -s           Use NTP_SERVER as the the server to use when updating the time.
 -h           Show this help menu.
Examples:
 boot2docker-ntp -s
 > Resets time based on default ntp server (0.pool.ntp.org)
 boot2docker-ntp -s 1.pool.ntp.org
> Resets time based on specified ntp server (1.pool.ntp.org)
UsageHERE
}


while getopts "s:h" opt
do
    case $opt in
        s)
            NTP_SERVER="$OPTARG"
            ;;
        h)
            usage
            exit 1
    esac
done


if [ -z "$NTP_SERVER" ]
then
    NTP_SERVER="0.pool.ntp.org"
fi


echo "Updating time based on NTP Server $NTP_SERVER"


docker run --rm --privileged cpuguy83/ntpdate "$NTP_SERVER"
if [ $? -eq 0 ]
then
    echo "Updated time. :)"
else
    echo "Error updating time!"
fi
exit $?